name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./ # Or 'docs' if your index.html is in a docs folder

      - name: Dummy upload (bypass error)
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
